### ISSUE TITLE
Would ZOOpt support PyTorch?

### ISSUE THREAD

**Issue by songyuc** [polixir/ZOOpt#6]
Hi guys,
I am a learner of PyTorch. So I am wondering whether ZOOpt would support PyTorch.

Any answer and guide will be appreciated!

**Comment by eyounx** [comment]
Hi,

ZOOpt is a derivative-free search toolbox, while PyTorch is a neural network framework. The two seem to be in parallel. You can use ZOOpt as an optimizer for, e.g., neural architecture search of networks built on top of PyTorch.

To do so, another option is to look at the [ray-project](github.com/ray-project/ray), in which ZOOpt is one of the optimizers in the Tune.

**Comment by songyuc** [comment]
> Hi,
> 
> 
> 
> ZOOpt is a derivative-free search toolbox, while PyTorch is a neural network framework. The two seem to be in parallel. You can use ZOOpt as an optimizer for, e.g., neural architecture search of networks built on top of PyTorch.
> 
> 
> 
> To do so, another option is to look at the [ray-project](github.com/ray-project/ray), in which ZOOpt is one of the optimizers in the Tune.

I have used particle swarm optimization (PSO) for the hyperparameters search. May I replace the PSO with ZOOpt to see whether it can outperform in my task?

**Comment by zewenli98** [comment]
> I have used particle swarm optimization (PSO) for the hyperparameters search. May I replace the PSO with ZOOpt to see whether it can outperform in my task?

If you want to harness ZOOpt to do hyperparameters searching, maybe you could modify the example in the README like: 
``` python3
def train_model(solution):
    # x is a set of hyperparams
    x = solution.get_x()
    # train your model with x
    # ...
    # calc the final metric
    # ...
    return metric

from zoopt import Dimension, ValueType, Dimension2, Objective, Parameter, Opt, ExpOpt

dim_size = 100  # dimension size
dim = Dimension(dim_size, [[-1, 1]]*dim_size, [True]*dim_size)  
# dim = Dimension2([(ValueType.CONTINUOUS, [-1, 1], 1e-6)]*dim_size)
obj = Objective(train_model, dim)
# perform optimization
solution = Opt.min(obj, Parameter(budget=100*dim_size))
# print the solution
print(solution.get_x(), solution.get_value())
# parallel optimization for time-consuming tasks
solution = Opt.min(obj, Parameter(budget=100*dim_size, parallel=True, server_num=3))
```

In addition, as prof. @eyounx said in https://github.com/polixir/ZOOpt/issues/6#issuecomment-1111243748, you could try Ray with ZOOpt optimizer to parallelize your hyperparams searching. [This doc](https://docs.ray.io/en/latest/tune/examples/includes/zoopt_example.html) might be useful.

**Comment by songyuc** [comment]
> > I have used particle swarm optimization (PSO) for the hyperparameters search. May I replace the PSO with ZOOpt to see whether it can outperform in my task?
> 
> 
> 
> If you want to harness ZOOpt to do hyperparameters searching, maybe you could modify the example in the README like: 
> 
> ``` python3
> 
> def train_model(solution):
> 
>     # x is a set of hyperparams
> 
>     x = solution.get_x()
> 
>     # train your model with x
> 
>     # ...
> 
>     # calc the final metric
> 
>     # ...
> 
>     return metric
> 
> 
> 
> from zoopt import Dimension, ValueType, Dimension2, Objective, Parameter, Opt, ExpOpt
> 
> 
> 
> dim_size = 100  # dimension size
> 
> dim = Dimension(dim_size, [[-1, 1]]*dim_size, [True]*dim_size)  
> 
> # dim = Dimension2([(ValueType.CONTINUOUS, [-1, 1], 1e-6)]*dim_size)
> 
> obj = Objective(train_model, dim)
> 
> # perform optimization
> 
> solution = Opt.min(obj, Parameter(budget=100*dim_size))
> 
> # print the solution
> 
> print(solution.get_x(), solution.get_value())
> 
> # parallel optimization for time-consuming tasks
> 
> solution = Opt.min(obj, Parameter(budget=100*dim_size, parallel=True, server_num=3))
> 
> ```
> 
> 
> 
> In addition, as prof. @eyounx said in https://github.com/polixir/ZOOpt/issues/6#issuecomment-1111243748, you could try Ray with ZOOpt optimizer to parallelize your hyperparams searching. [This doc](https://docs.ray.io/en/latest/tune/examples/includes/zoopt_example.html) might be useful.

Okay, I will learn using ZOOpt.
Thanks sincerely for your patient guidance.
